export const SITE_CONFIG = {
  name: "GirlyHub",
  legalName: "GirlyHub Retail Private Limited",
  domain: "girlyhub.in",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://girlyhub.in",
  tagline: "Trendy Jewellery, Hair Accessories & Scrunchies",
  defaultTitle: "GirlyHub: Jewellery & Accessories",
  // defaultDescription: "Shop hair accessories, Korean claws, scrunchies, jewellery, earrings, and lifestyle essentials at GirlyHub with COD delivery across India.",
  defaultDescription:
    "Shop hair accessories, Korean claws, scrunchies, jewellery, earrings, and lifestyle essentials at GirlyHub with fast delivery across India.",
  defaultKeywords: [
    "GirlyHub",
    "hair accessories",
    "hair claws online",
    "aesthetic jewellery",
    "scrunchies combo",
    "korean hair clips",
    "earrings online india",
    "trendy accessories for girls",
    "cute lifestyle products",
    "affordable jewellery store",
  ],
  logo: "https://girlyhub.in/girlyhub_logo_flower_transparent.png",
  ogImage: "https://girlyhub.in/og.png",
  socials: {
    instagram: "https://www.instagram.com/officialgirlyhub",
    facebook: "https://www.facebook.com/officialgirlyhub",
    pinterest: "https://www.pinterest.com/officialgirlyhub",
  },
  contact: {
    email: "officialgirlyhub@gmail.com",
    phone: "+918368422490",
    address: {
      streetAddress: "Jwala Nagar Shahdara",
      addressLocality: "Delhi",
      addressRegion: "Delhi",
      postalCode: "110032",
      addressCountry: "IN",
    },
  },
};
